spring:
  redis:
    sentinel:
      nodes:
        - redis-sentinel1:26379
        - redis-sentinel2:26379
        - redis-sentinel3:26379
      master: mymaster
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes: