apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: cluster
spec:
  ports:
    - name: slave1-6379
      port: 6379
      targetPort: 6379
  selector:
    app: redis-slave1
  type: NodePort
---