version: '3.1'

services:
  es-node1:
    image: elasticsearch:6.6.2
    container_name: es-node1
    environment:
      - cluster.name=docker-cluster
      - node.master=true
      - node.data=true
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[es-node1:9300,es-node2:9300,es-node3:9300]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
  es-node2:
    image: elasticsearch:6.6.2
    container_name: es-node2
    environment:
      - cluster.name=docker-cluster
      - node.master=true
      - node.data=true
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[es-node1:9300,es-node2:9300,es-node3:9300]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
  es-node3:
    image: elasticsearch:6.6.2
    container_name: es-node3
    environment:
      - cluster.name=docker-cluster
      - node.master=true
      - node.data=true
      - discovery.zen.minimum_master_nodes=2
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.zen.ping.unicast.hosts=[es-node1:9300,es-node2:9300,es-node3:9300]"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    ports:
      - 9200
    networks:
      - esnet
volumes:
  esdata1:
    driver: local
  esdata2:
    driver: local
  esdata3:
    driver: local

networks:
  esnet: