version: '3.1'

services:
  redis-slave1:
    image: redis-cluster-slave:latest
    container_name: redis-slave1
    ports:
      - 6379
    networks:
      - redisnet
  redis-slave2:
    image: redis-cluster-slave:latest
    container_name: redis-slave2
    ports:
      - 6379
    networks:
      - redisnet
  redis-slave3:
    image: redis-cluster-slave:latest
    container_name: redis-slave3
    ports:
      - 6379
    networks:
      - redisnet
  redis-sentinel1:
    image: redis-cluster-sentinel:latest
    container_name: redis-sentinel1
    ports:
      - 26379
    networks:
      - redisnet
    environment:
      - "Monitor='redis-slave1 6379 2'"
      - "KnownSlave='redis-slave2 redis-slave3'"
      - "KnownSentinel='redis-sentinel2 redis-sentinel3'"
  redis-sentinel2:
    image: redis-cluster-sentinel:latest
    container_name: redis-sentinel2
    ports:
      - 26379
    networks:
      - redisnet
    environment:
      - "Monitor='redis-slave1 6379 2'"
      - "KnownSlave='redis-slave2 redis-slave3'"
      - "KnownSentinel='redis-sentinel1 redis-sentinel3'"
  redis-sentinel3:
    image: redis-cluster-sentinel:latest
    container_name: redis-sentinel3
    ports:
      - 26379
    networks:
      - redisnet
    environment:
      - "Monitor='redis-slave1 6379 2'"
      - "KnownSlave='redis-slave2 redis-slave3'"
      - "KnownSentinel='redis-sentinel1 redis-sentinel2'"

networks:
  redisnet: